name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically ran and kicked ass. This event tagged along: ${{ github.event_name}}."
      - run: echo "Properties: OS: ${{ runner.os}}, Branch: ${{ github.ref}}, Repo: ${{ github.repository }}"
      - name: Check out repository code
      - uses: actions/checkoutv5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
