name: Autoprefix PR Title
on: 
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  prefix-title:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Add prefix to PR  label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;
            const currentTitle = pr.title;

            let prefix = null;

            if (branch.startsWith('feat/')) prefix = '[Feature]';
            else if (branch.startsWith('fix/') prefix = '[Fix]';
            else if (branch.startsWith('bug/') prefix = '[Bug]';

            if (prefix && !currentTitle.startsWith(prefix)) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: `${prefix} ${currentTitle}`
              });
              console.log(`Updated title to: ${prefix} ${currentTitle}`);
            }
